Завершил верстку index.html и catalog.html
htmlacademy-htmlcss/2238149-sedona-35 pull request #3
Opened 2022-10-08 09:23 UTC by Serjulik

2022-10-08 12:41 UTC, DoberBober commented on catalog.html
> +            <a class="navigation-link navigation-link-current" href="catalog.html">Гостиницы</a>
```suggestion
             <a class="navigation-link navigation-link-current">Гостиницы</a>
```
У текущего пункта href вообще не нужен.

2022-10-08 12:41 UTC, DoberBober commented on catalog.html
> +                  <input class="control-input" type="checkbox" name="pool" checked>
Инпуты поставь перед лейблами и свяжи их через id/for.

2022-10-08 12:42 UTC, DoberBober commented on catalog.html
> +                    <input class="control-input" type="radio" name="product-group" value="hotel" checked>
Здесь тоже.

2022-10-08 12:42 UTC, DoberBober commented on catalog.html
> +          <button class="button" type="submit">ПРИМЕНИТЬ</button>
Не пиши капсом. Это можно через цсс сделать.

2022-10-08 12:43 UTC, DoberBober commented on catalog.html
> +          <a class="product-card-link" href="product.html">
Формально это не ошибка, но всё же: будет лучше, если ты сделаешь две ссылки. Одна вокруг картинки, вторая внутри h3.

2022-10-08 12:43 UTC, DoberBober commented on catalog.html
> +            <span class="visually-hidden">Подписаться</span>
А зачем visually-hidden? У тебя ж текст должен отображаться.

2022-10-08 12:44 UTC, DoberBober commented on catalog.html
> +          <a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy</a>
Свгшка.

Копирайт вытащи из сойсетей и поставь после телефона.

2022-10-08 12:45 UTC, DoberBober commented on index.html
> +      <img class="logo" src="" alt="Логотип Sedona">
Картинку лучше обернуть в див, которому потом задашь фон с горами.

2022-10-08 12:47 UTC, DoberBober commented on index.html
> +        <ul class="advantages-list">
1. Тут отступы вообще у тебя поехали. Старайся держать ровно всё.
2. Так, у тебя тут _список_ из пяти элементов. В первом и пятом _пунктах_ есть див, который группирует тексты, и картинка. В пятом пункте есть ещё и _подсписок_ из трёх пунктов.

2022-10-08 12:47 UTC, DoberBober commented on index.html
> +                        <li class="advantages-item">
Это уже вытащи в отдельный секшн. Это не часть предыдущего списка.

2022-10-08 12:47 UTC, DoberBober commented on index.html
> +              <span class="visually-hidden">Подписаться</span>
Повторяющиеся ошибки не буду писать, надо будет на обеих страницах поправить.

2022-10-08 12:48 UTC, DoberBober requested changes
Очень хорошо. Пара мелочей надо поправить только.

2022-10-09 08:46 UTC, Serjulik commented on catalog.html
> +            <a class="navigation-link navigation-link-current" href="catalog.html">Гостиницы</a>
Убрал href

2022-10-09 09:12 UTC, Serjulik commented on catalog.html
> +          <button class="button" type="submit">ПРИМЕНИТЬ</button>
Поправил в обоих документах

2022-10-10 07:32 UTC, Serjulik commented on catalog.html
> +                  <input class="control-input" type="checkbox" name="pool" checked>
Исправлено

2022-10-10 08:04 UTC, Serjulik commented on catalog.html
> +                    <input class="control-input" type="radio" name="product-group" value="hotel" checked>
Исправлено

2022-10-10 08:44 UTC, Serjulik commented on catalog.html
> +          <a class="product-card-link" href="product.html">
Сделал две ссылки. Вокруг картинки и внутри h3

2022-10-10 10:01 UTC, Serjulik commented on catalog.html
> +            <span class="visually-hidden">Подписаться</span>
убрал class="visually-hidden" в двух документах

2022-10-10 10:01 UTC, Serjulik commented on index.html
> +              <span class="visually-hidden">Подписаться</span>
убрал class="visually-hidden" в двух документах

2022-10-10 10:35 UTC, Serjulik commented on catalog.html
> +          <a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy</a>
Поставил после телефона, добавил svg

2022-10-10 10:40 UTC, Serjulik commented on index.html
> +      <img class="logo" src="" alt="Логотип Sedona">
Обернул в div

2022-10-10 10:42 UTC, Serjulik commented on index.html
> +        <ul class="advantages-list">
Тут я использовал Prettier, сложно сказать, но вроде стало более правильно.

2022-10-10 11:33 UTC, Serjulik commented on index.html
> +                        <li class="advantages-item">
Поправил. Хотя и с твоей помощью.

2022-10-10 19:58 UTC, DoberBober approved these changes
Отпишусь в личку. Есть небольшой недочёт.

2022-10-10 19:59 UTC, merged